# Generated by Django 4.1.2 on 2022-11-17 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_page'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
